
USE ouroboros;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    USER_ID     INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USERNAME    VARCHAR(50)        NOT NULL,
    FIRSTNAME   VARCHAR(50),
    LASTNAME    VARCHAR(50),
    EMAIL       VARCHAR(50)        NOT NULL,
    HASH        VARCHAR(100)       NOT NULL,
    TOKEN       VARCHAR(100),
    DOCTOR      VARCHAR(100),
    DOCTOREMAIL VARCHAR(100)
);


CREATE TABLE LISTS
(
    LIST_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    MEDICATION_ONE VARCHAR(50),
    MEDICATION_TWO VARCHAR(50),
    MEDICATION_THREE VARCHAR(50),
    MEDICATION_FOUR VARCHAR(50),
    MEDICATION_FIVE VARCHAR(50),
    MEDICATION_SIX VARCHAR(50),
    MEDICATION_SEVEN VARCHAR(50),
    MEDICATION_EIGHT VARCHAR(50),
    MEDICATION_NINE VARCHAR(50),
    MEDICATION_TEN VARCHAR(50)
);

ALTER TABLE LISTS ADD CONSTRAINT FK_LISTS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

INSERT INTO USERS (firstName, lastName, username, email, HASH) VALUES ('Bruce', 'Wayne', 'batman', 'batman@wayne.com','');
INSERT INTO USERS (firstName, lastName, username, email, HASH) VALUES ('Richard', 'Grayson', 'nightwing', 'nightwing@wayne.com','');
INSERT INTO USERS (firstName, lastName, username, email, HASH) VALUES ('Barbara', 'Gordon', 'batgirl', 'batgirl@wayne.com','');
INSERT INTO USERS (firstName, lastName, username, email, HASH) VALUES ('Jason', 'Todd', 'redhood', 'redhood@wayne.com','');
INSERT INTO USERS (firstName, lastName, username, email, HASH) VALUES ('Damian', 'Wayne', 'robin', 'robin@wayne.com','');


INSERT INTO LISTS (USER_ID, MEDICATION_ONE) VALUES ('1','VICODONE');
INSERT INTO LISTS (USER_ID, MEDICATION_ONE) VALUES ('2','DOLIPRANE');
INSERT INTO LISTS (USER_ID, MEDICATION_ONE) VALUES ('3','EFFERALGAN');
INSERT INTO LISTS (USER_ID, MEDICATION_ONE) VALUES ('4','HEROIN');
INSERT INTO LISTS (USER_ID, MEDICATION_ONE) VALUES ('5','POULET');
